### PR TITLE
Update dependencies

### LINKED ISSUE #122: Protobuf 5+
`Because ghome-foyer-api==1.0.0 depends on protobuf>=4.21.12,<5.0.0 and protobuf==5.28.3, we can conclude that ghome-foyer-api==1.0.0 cannot be used. And because only ghome-foyer-api==1.0.0 is available, we can conclude that all versions of ghome-foyer-api cannot be used.`

Can we get a build that allows for protobuf 5+? Thanks!

### PR DESCRIPTION
**Pull request by KapJI**
* Update dependencies include protobuf.
* Regenerate stubs.

Fixes #122

### CODE REVIEW

**Comment by satmandu** [comment]
Would you be so kind as to tag a new release?

**Comment by satmandu** [comment]
(I think only a release is going to trigger an upload to PyPi from https://github.com/KapJI/ghome-foyer-api/blob/main/.github/workflows/publish.yml )

**Comment by satmandu** [comment]
Also see https://github.com/leikoilja/ha-google-home/issues/918#issuecomment-2455721981

**Comment by KapJI** [comment]
@satmandu v1.1.0 is published.

**Comment by FrancoLoco** [comment]
many thanks!

**Pull request merged**
